/**
 * Build 04 release gate: proof that non-public content cannot reach the
 * public site.
 *
 * These are not ordinary unit tests. A failure here means the archive can
 * leak an investor memo or a restricted record onto the open internet,
 * which is the one failure this product cannot recover from. They assert
 * against the GENERATED BYTES, not just the selection function — because a
 * document could be correctly excluded from the index and still be leaked
 * by a stray link, a sitemap entry, or a copied PDF.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateSite, isEligible, publish, rendererAvailable } from '../src/index.js';
import { esc } from '../src/site/templates.js';
import { makeInstance, writePaper, validPaper } from './helpers.js';

const HAVE_RENDERER = rendererAvailable({});
const pdfTest = (name, fn) => test(name, { skip: HAVE_RENDERER ? false : 'no Chromium available' }, fn);

/** Every file the generator produced, as one searchable blob. */
function allOutput(outDir) {
  const out = [];
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) walk(p);
      else out.push({ path: p, text: p.endsWith('.pdf') ? '' : readFileSync(p, 'utf8') });
    }
  };
  if (existsSync(outDir)) walk(outDir);
  return out;
}

function bodyOf(text) {
  return `\n${text}\n`;
}

/* ---- the gate, directly ------------------------------------------- */

test('gate: only canon + public audience is eligible', () => {
  const { config, cleanup } = makeInstance();
  assert.equal(isEligible({ status: 'canon', audience: 'public' }, config), true);
  cleanup();
});

test('gate: every non-public audience is refused even when canon', () => {
  const { config, cleanup } = makeInstance();
  for (const audience of ['internal', 'investor', 'restricted']) {
    assert.equal(isEligible({ status: 'canon', audience }, config), false, audience);
  }
  cleanup();
});

test('gate: every non-canon status is refused even when public', () => {
  const { config, cleanup } = makeInstance();
  for (const status of ['draft', 'review', 'superseded', 'amended']) {
    assert.equal(isEligible({ status, audience: 'public' }, config), false, status);
  }
  cleanup();
});

test('gate: malformed and missing audience fail closed', () => {
  const { config, cleanup } = makeInstance();
  for (const audience of [undefined, null, '', '   ', 'pubic', 'PUBLIC', 'Public', 0, false, {}]) {
    assert.equal(isEligible({ status: 'canon', audience }, config), false, JSON.stringify(audience));
  }
  assert.equal(isEligible(null, config), false);
  assert.equal(isEligible({}, config), false);
  cleanup();
});

test('gate: when no public audience is configured, nothing is eligible', () => {
  const { config, cleanup } = makeInstance({ public_audience: undefined });
  assert.equal(isEligible({ status: 'canon', audience: 'public' }, config), false);
  cleanup();
});

/* ---- generated output --------------------------------------------- */

pdfTest('no internal, investor, or restricted content appears in any generated file', () => {
  const { dir, config, cleanup } = makeInstance();

  const secrets = {
    internal: 'INTERNALSECRETMARKER',
    investor: 'INVESTORSECRETMARKER',
    restricted: 'RESTRICTEDSECRETMARKER',
  };

  let seq = 1;
  for (const [audience, marker] of Object.entries(secrets)) {
    const id = `NW-2026-08-18-PHI-00${seq}`;
    publish(
      writePaper(dir, `${audience}.md`, validPaper({ id, date: '2026-08-18', audience }), bodyOf(`Body containing ${marker}.`)),
      config,
    );
    seq += 1;
  }
  // One genuinely public paper, so the site is not trivially empty.
  publish(
    writePaper(dir, 'public.md', validPaper({ id: 'NW-2026-08-18-PHI-004', date: '2026-08-18', audience: 'public', title: 'Public Paper' }), bodyOf('Safe public body.')),
    config,
  );

  const result = generateSite(config, { outDir: join(dir, 'site'), baseUrl: 'https://example.test' });
  assert.deepEqual(result.published, ['NW-2026-08-18-PHI-004']);

  const files = allOutput(result.outDir);
  assert.ok(files.length > 0, 'site generated files');

  for (const marker of Object.values(secrets)) {
    for (const f of files) {
      assert.ok(!f.text.includes(marker), `LEAK: ${marker} found in ${f.path}`);
    }
  }
  // Not even the IDs of non-public documents should appear.
  for (const id of ['NW-2026-08-18-PHI-001', 'NW-2026-08-18-PHI-002', 'NW-2026-08-18-PHI-003']) {
    for (const f of files) {
      assert.ok(!f.text.includes(id), `LEAK: non-public id ${id} referenced in ${f.path}`);
    }
  }
  cleanup();
});

pdfTest('no PDF of a non-public document is copied into the output tree', () => {
  const { dir, config, cleanup } = makeInstance();
  publish(writePaper(dir, 'i.md', validPaper({ id: 'NW-2026-08-18-PHI-001', date: '2026-08-18', audience: 'investor' })), config);
  publish(writePaper(dir, 'p.md', validPaper({ id: 'NW-2026-08-18-PHI-002', date: '2026-08-18', audience: 'public' })), config);

  const result = generateSite(config, { outDir: join(dir, 'site') });
  const pdfs = allOutput(result.outDir).filter((f) => f.path.endsWith('.pdf')).map((f) => f.path);

  assert.ok(pdfs.some((p) => p.includes('NW-2026-08-18-PHI-002')), 'public pdf published');
  assert.ok(!pdfs.some((p) => p.includes('NW-2026-08-18-PHI-001')), 'LEAK: investor pdf copied to public output');
  cleanup();
});

pdfTest('a draft marked public is still excluded — approval is required', () => {
  const { dir, config, cleanup } = makeInstance();
  publish(writePaper(dir, 'p.md', validPaper({ id: 'NW-2026-08-18-PHI-001', date: '2026-08-18', audience: 'public' })), config);

  // Force the manifest entry back to draft, simulating an unapproved record.
  const mPath = join(dir, 'manifests', 'library-manifest.json');
  const m = JSON.parse(readFileSync(mPath, 'utf8'));
  m.entries['NW-2026-08-18-PHI-001'].status = 'draft';
  writeFileSync(mPath, JSON.stringify(m, null, 2));

  const result = generateSite(config, { outDir: join(dir, 'site') });
  assert.deepEqual(result.published, []);
  cleanup();
});

pdfTest('a superseded public document leaves the site; its successor appears', () => {
  const { dir, config, cleanup } = makeInstance();
  publish(writePaper(dir, 'v1.md', validPaper({ id: 'NW-2026-08-18-PHI-001', date: '2026-08-18', audience: 'public', title: 'First' }), bodyOf('OLDPUBLICBODY')), config);

  let result = generateSite(config, { outDir: join(dir, 'site') });
  assert.deepEqual(result.published, ['NW-2026-08-18-PHI-001']);

  publish(
    writePaper(dir, 'v2.md', validPaper({
      id: 'NW-2026-08-19-PHI-002', date: '2026-08-19', audience: 'public',
      title: 'Second', supersedes: 'NW-2026-08-18-PHI-001',
    }), bodyOf('NEWPUBLICBODY')),
    config,
  );

  result = generateSite(config, { outDir: join(dir, 'site2') });
  assert.deepEqual(result.published, ['NW-2026-08-19-PHI-002'], 'superseded document is withdrawn from the public index');

  const files = allOutput(result.outDir);
  assert.ok(files.some((f) => f.text.includes('NEWPUBLICBODY')));
  assert.ok(!files.some((f) => f.text.includes('OLDPUBLICBODY')), 'superseded body must not be served');
  cleanup();
});

pdfTest('the sitemap lists only eligible documents', () => {
  const { dir, config, cleanup } = makeInstance();
  publish(writePaper(dir, 'i.md', validPaper({ id: 'NW-2026-08-18-PHI-001', date: '2026-08-18', audience: 'restricted' })), config);
  publish(writePaper(dir, 'p.md', validPaper({ id: 'NW-2026-08-18-PHI-002', date: '2026-08-18', audience: 'public' })), config);

  const result = generateSite(config, { outDir: join(dir, 'site'), baseUrl: 'https://example.test' });
  const sitemap = readFileSync(join(result.outDir, 'sitemap.xml'), 'utf8');
  assert.ok(sitemap.includes('NW-2026-08-18-PHI-002'));
  assert.ok(!sitemap.includes('NW-2026-08-18-PHI-001'), 'LEAK: restricted id in sitemap');
  cleanup();
});

pdfTest('an empty public corpus produces a site that says so rather than leaking', () => {
  const { dir, config, cleanup } = makeInstance();
  publish(writePaper(dir, 'i.md', validPaper({ id: 'NW-2026-08-18-PHI-001', date: '2026-08-18', audience: 'internal' })), config);

  const result = generateSite(config, { outDir: join(dir, 'site') });
  assert.deepEqual(result.published, []);
  const home = readFileSync(join(result.outDir, 'index.html'), 'utf8');
  assert.match(home, /No public records have been published yet/);
  assert.ok(!home.includes('NW-2026-08-18-PHI-001'));
  cleanup();
});

test('no sitemap is written when no base URL is configured', () => {
  const { dir, config, cleanup } = makeInstance();
  const result = generateSite(config, { outDir: join(dir, 'site') });
  assert.ok(!existsSync(join(result.outDir, 'sitemap.xml')), 'a relative sitemap is worse than none');
  assert.ok(existsSync(join(result.outDir, 'robots.txt')));
  cleanup();
});

/* ---- structure, a11y, SEO ----------------------------------------- */

test('every page has the accessibility and SEO essentials', () => {
  const { dir, config, cleanup } = makeInstance();
  const result = generateSite(config, { outDir: join(dir, 'site'), baseUrl: 'https://example.test' });

  for (const f of allOutput(result.outDir).filter((x) => x.path.endsWith('.html'))) {
    assert.match(f.text, /<html lang="en">/, `lang attribute missing in ${f.path}`);
    assert.match(f.text, /<meta name="viewport"/, `viewport missing in ${f.path}`);
    assert.match(f.text, /<title>[^<]+<\/title>/, `title missing in ${f.path}`);
    assert.match(f.text, /<meta name="description" content="[^"]+"/, `description missing in ${f.path}`);
    assert.match(f.text, /rel="canonical"/, `canonical missing in ${f.path}`);
    assert.match(f.text, /class="skip-link"/, `skip link missing in ${f.path}`);
    assert.match(f.text, /<main id="main">/, `main landmark missing in ${f.path}`);
    assert.match(f.text, /aria-label="Primary"/, `nav landmark missing in ${f.path}`);
    assert.match(f.text, /og:title/, `open graph missing in ${f.path}`);
    assert.ok((f.text.match(/<h1[ >]/g) ?? []).length === 1, `exactly one h1 required in ${f.path}`);
  }
  cleanup();
});

test('the stylesheet is light-first with no dark-mode variant', () => {
  const { dir, config, cleanup } = makeInstance();
  const result = generateSite(config, { outDir: join(dir, 'site') });
  const css = readFileSync(join(result.outDir, 'styles.css'), 'utf8');

  // torus-factory forbids dark mode with a build-failing test; the public
  // Library inherits that constraint (ADR-0008).
  assert.ok(!/prefers-color-scheme\s*:\s*dark/.test(css), 'dark mode must not reappear');
  assert.ok(!/\.dark\b/.test(css), 'no .dark class');
  assert.match(css, /--background:\s*#f4f5f6/, 'inherits the Precision Light canvas');
  assert.match(css, /--primary:\s*oklch\(0\.52 0\.2 27\.325\)/, 'inherits Torus red');
  assert.match(css, /prefers-reduced-motion/, 'respects reduced motion');
  cleanup();
});

test('escaping prevents HTML injection through document metadata', () => {
  assert.equal(esc('<script>alert(1)</script>'), '&lt;script&gt;alert(1)&lt;/script&gt;');
  assert.equal(esc('" onload="x'), '&quot; onload=&quot;x');
});
