/**
 * The manifest: the register of every paper the library holds.
 *
 * Stored as JSON (machine source of truth) and rendered to Markdown for
 * humans. The JSON is authoritative; the Markdown is generated from it and
 * must never be hand-edited.
 *
 * Writes are atomic (temp file + rename) so an interrupted publish cannot
 * leave a half-written register behind.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const EMPTY = { schema_version: 1, entries: {} };

function jsonPath(config) {
  return config.resolved.manifest;
}

function markdownPath(config) {
  return jsonPath(config).replace(/\.json$/, '.md');
}

export function load(config) {
  const path = jsonPath(config);
  if (!existsSync(path)) return structuredClone(EMPTY);
  const parsed = JSON.parse(readFileSync(path, 'utf8'));
  return { ...structuredClone(EMPTY), ...parsed };
}

function writeAtomic(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = join(dirname(path), `.${Date.now()}.tmp`);
  writeFileSync(tmp, contents, 'utf8');
  renameSync(tmp, path);
}

export function save(manifest, config) {
  writeAtomic(jsonPath(config), `${JSON.stringify(manifest, null, 2)}\n`);
  writeAtomic(markdownPath(config), renderMarkdown(manifest, config));
  return manifest;
}

export function getEntry(manifest, id) {
  return manifest.entries[id] ?? null;
}

export function upsertEntry(manifest, entry) {
  manifest.entries[entry.id] = entry;
  return manifest;
}

/** Papers are listed newest first, then by ID for stable ordering. */
function sortedEntries(manifest) {
  return Object.values(manifest.entries).sort((a, b) => {
    if (a.date !== b.date) return a.date < b.date ? 1 : -1;
    return a.id < b.id ? -1 : 1;
  });
}

export function renderMarkdown(manifest, config) {
  const org = config.organisation?.name ?? 'Library';
  const entries = sortedEntries(manifest);

  const header = `# ${org} — Library Manifest

Generated by the Torus Library engine. **Do not hand-edit** — this file is
rendered from \`${jsonPath(config).split('/').pop()}\`, which is the source of truth.

Two hashes are recorded per paper, with different meanings (ADR-0003):
\`source\` is the SHA-256 of the Markdown source and is reproducible;
\`pdf\` is the SHA-256 of the frozen PDF artifact and is tamper-evidence
for that specific file.

Papers: **${entries.length}**
`;

  if (entries.length === 0) {
    return `${header}
_No papers have been canonized yet._
`;
  }

  const rows = entries
    .map((e) => {
      const supersedes = e.supersedes ?? '—';
      const amends = e.amends ?? '—';
      const src = e.source_sha256 ? `\`${e.source_sha256.slice(0, 12)}…\`` : '—';
      const pdf = e.pdf_sha256 ? `\`${e.pdf_sha256.slice(0, 12)}…\`` : '—';
      return `| \`${e.id}\` | ${e.title} | ${e.date} | ${e.status} | ${e.audience} | ${supersedes} | ${amends} | ${src} | ${pdf} |`;
    })
    .join('\n');

  return `${header}
| ID | Title | Date | Status | Audience | Supersedes | Amends | Source SHA-256 | PDF SHA-256 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows}
`;
}
